
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import *
from tkinter import Frame
import tkinter as tk
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from tkinter import ttk
import mysql.connector
from tkinter.font import Font
from mysql.connector import Error
from tkinter import messagebox
from datetime import datetime


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"E:\Python\PMLCR\Projects\Inventory System\assets\frame0")

def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

window = Tk()

window.geometry("1280x720")
window.configure(bg = "#FFFFFF")
window.title("Inventory System")
try:
    icon_image = PhotoImage(file=relative_to_assets("button_3.png"))
    window.iconphoto(True, icon_image)
except Exception as e:
    print(f"Error loading image: {e}")

canvas = Canvas(window, bg = "#FFFFFF", height = 720, width = 1280, bd = 0, highlightthickness = 0, relief = "ridge")

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button( image=button_image_1, borderwidth=0, highlightthickness=0, command=lambda: show_frame(additem), relief="flat", bg="#ffffff", activebackground="#ffffff")
button_1.place( x=1042.0, y=50.0, width=48.0, height=48.0)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button( image=button_image_2, borderwidth=0, highlightthickness=0, command=lambda: show_frame(setting), relief="flat", bg="#ffffff", activebackground="#ffffff")
button_2.place( x=1133.0, y=50.0, width=48.0, height=48.0)

button_image_3 = PhotoImage(file=relative_to_assets("button_3.png"))
button_3 = Button( image=button_image_3, borderwidth=0, highlightthickness=0, command=lambda: show_frame(inventory), relief="flat", bg="#ffffff", activebackground="#ffffff")
button_3.place( x=161.0, y=50.0, width=48.0, height=48.0)

button_image_4 = PhotoImage( file=relative_to_assets("button_4.png"))
button_4 = Button( image=button_image_4, borderwidth=0, highlightthickness=0, command=lambda: show_frame(homepage), relief="flat", bg="#ffffff", activebackground="#ffffff")
button_4.place( x=73.0, y=50.0, width=48.0, height=48.0)

button_image_5 = PhotoImage( file=relative_to_assets("button_5.png"))
button_5 = Button( image=button_image_5, borderwidth=0, highlightthickness=0, command=lambda: print(" "), relief="flat", bg="#ffffff", activebackground="#ffffff")
button_5.place( x=248.0, y=49.0, width=753.0, height=53.0)

entry = Entry(window, bd=0, relief="flat", font=("Helvetica", 20))
entry.place(x=310, y=54, width=650, height=42)

def get_input():
    user_input = entry.get()
    print(f"User input: {user_input}")

def show_frame(homepage):
    homepage.tkraise()
def show_frame(inventory):
    inventory.tkraise()
def show_frame(additem):
    additem.tkraise()
def show_frame(setting):
    setting.tkraise()

# Creating Sub frames for HomePage, Inventory, AddItems, Setting.
homepage = tk.Frame(window, bg="#fff", width=1130, height=500)
inventory = tk.Frame(window, bg="#fff", width=1130, height=500)
additem = tk.Frame(window, bg="#fff", width=1130, height=500)
setting = tk.Frame(window, bg="#fff", width=1130, height=500)

# Position the frames inside the main frame
homepage.grid(row=0, column=0, padx=70, pady=150, sticky="nsew")
inventory.grid(row=0, column=0, padx=70, pady=150, sticky="nsew")
additem.grid(row=0, column=0, padx=70, pady=150, sticky="nsew")
setting.grid(row=0, column=0, padx=70, pady=150, sticky="nsew")

#Creating Sub Frames for show dashboard
dashb01 = tk.Frame(homepage, bg="#ffffff", width=1130, height=150)
dashb01.place(x=30, y=0)
dashb02 = tk.Frame(homepage, bg="#ffffff", width=230, height=350)
dashb02.place(x=20, y=200)
dashb03 = tk.Frame(homepage, bg="#ffffff", width=330, height=350)
dashb03.place(x=600, y=200)

try:
    connection = mysql.connector.connect(
        host="localhost",
        user="root",  # username
        password="",  # password
        database="inventory"  # database name
    )

    if connection.is_connected():
        cursor = connection.cursor()

        query = """
        SELECT 
            COUNT(ProductID) AS ProductCount,
            COUNT(DISTINCT category) AS CateCount,
            SUM(price) AS TotalPrice
        FROM products
        """
        cursor.execute(query)

        result = cursor.fetchone()

        ProductCount = [result[0]]
        CateCount = [result[1]]
        TotalPrice = [int(result[2])]
        TotalCost = [int(TotalPrice[0] * 0.85)]

except Error as e:
    messagebox.showerror("Database Error", f"Error: {e}")

finally:
    if connection.is_connected():
        cursor.close()
        connection.close()

button_image_6 = PhotoImage(file=relative_to_assets("button_6.png"))
button_6 = Button( dashb01, image=button_image_6, borderwidth=0, highlightthickness=0, command=lambda: print("button_6 clicked"), relief="flat")
button_6.place( x=66.0, y=15.0, width=160.0, height=90.0)
tk.Label(dashb01, text=ProductCount, font=("Arial", 28), bg="white").place(x=170, y=50)

button_image_7 = PhotoImage( file=relative_to_assets("button_7.png"))
button_7 = Button(dashb01, image=button_image_7, borderwidth=0, highlightthickness=0, command=lambda: print("button_7 clicked"), relief="flat")
button_7.place( x=254.0, y=15.0, width=160.0, height=90.0)
tk.Label(dashb01, text=CateCount, font=("Arial", 28), bg="white").place(x=360, y=50)

button_image_8 = PhotoImage( file=relative_to_assets("button_8.png"))
button_8 = Button(dashb01, image=button_image_8, borderwidth=0, highlightthickness=0, command=lambda: print("button_8 clicked"), relief="flat")
button_8.place(  x=442.0, y=15.0, width=160.0, height=90.0)
tk.Label(dashb01, text=TotalCost, font=("Arial", 22), bg="white").place(x=475, y=60)

button_image_9 = PhotoImage( file=relative_to_assets("button_9.png"))
button_9 = Button(dashb01, image=button_image_9, borderwidth=0, highlightthickness=0, command=lambda: print("button_9 clicked"), relief="flat")
button_9.place(  x=630.0,  y=15.0,  width=160.0, height=90.0)
tk.Label(dashb01, text=TotalPrice, font=("Arial", 22), bg="white").place(x=665, y=60)

button_image_10 = PhotoImage(  file=relative_to_assets("button_10.png"))
button_10 = Button(dashb01,  image=button_image_10, borderwidth=0, highlightthickness=0, command=lambda: print("button_10 clicked"), relief="flat")
button_10.place( x=818.0, y=15.0, width=160.0, height=90.0)
tk.Label(dashb01, text="00", font=("Arial", 28), bg="white").place(x=923, y=50)


# --------------------------------------------------------------
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

# Data lists for the chart
data1 = [10, 20, 30, 10, 50]
data2 = [5, 12, 40, 50, 30]
data3 = [25, 32, 45, 15, 80]

# Create the content area (right side)
content_area = tk.Frame(dashb02)
content_area.pack(side="right", fill="both", expand=True)

# Frame for displaying the chart
chart_frame = tk.Frame(content_area, bg="#ffffff")
chart_frame.grid(row=0, column=0, sticky="nsew")  # Use grid instead of pack/place

# Function to create and display a chart
fig, ax = plt.subplots(figsize=(5, 3))  # Set the size of the figure

# Plot the data series
line1, = ax.plot(data1, label="Sells", color='blue')  # Adding label for legend
line2, = ax.plot(data2, label="Market", color='green')  # Adding label for legend
line3, = ax.plot(data3, label="Profit", color='red')  # Adding label for legend

# Set title and grid
ax.set_title("Sell Status", loc='left')
ax.grid(True)

# Add a legend with a color box and label in front of each color
ax.legend(loc="upper right")

# Embed the chart in the Tkinter frame using grid
canvas = FigureCanvasTkAgg(fig, master=chart_frame)
canvas.get_tk_widget().grid(row=1, column=2, sticky="nsew")  # Ensure canvas fills the grid cell

canvas.draw()
# --------------------------------------------------------------

# --------------------------------------------------------------
categories = ['HDD', 'SSD', 'CPU', 'FAN', 'Case', 'RAM']
values = [8, 18, 10, 25, 12, 20]

fig, ax = plt.subplots(figsize=(5, 3))
# Create a horizontal bar chart
ax.barh(categories, values, color='skyblue')

# Set title and labels
ax.set_title("Top Products in Month", loc='left')

# Embed the plot in the Tkinter window
canvas = FigureCanvasTkAgg(fig, master=dashb03)
canvas.get_tk_widget().pack(side="right", fill="both", expand=True)
canvas.draw()
#-----------------------------------------------------------------

frame = tk.Frame(inventory)
frame.pack(fill="both", expand=True)

# Fetch data from MySQL Database
# Paste Fatch Data function below----------------------------------------------------------------------------

def fetch_data(query=""):
    try:
        # Establish connection to MySQL database
        connection = mysql.connector.connect(
            host="localhost",
            user="root",  # Replace with your MySQL username
            password="",  # Replace with your MySQL password
            database="inventory"  # Replace with your database name
        )

        # Check if connection was successful
        if connection.is_connected():
            cursor = connection.cursor()

            # If no search query is provided, fetch all records
            if query == "":
                cursor.execute("SELECT productID, ProductName, Category,  Price, Quantity, Warranty FROM products ORDER BY productID")
            else:
                cursor.execute(f"SELECT productID, ProductName, Category,  Price, Quantity, Warranty FROM products WHERE ProductName LIKE %s OR Category LIKE %s",
    ('%' + query + '%', '%' + query + '%',))


            result = cursor.fetchall()

            # Clear the previous results in the treeview
            for item in treeview.get_children():
                treeview.delete(item)

            # Insert the new results
            for row in result:
                treeview.insert("", "end", values=row)

            # Close the cursor
            cursor.close()
        else:
            raise Exception("Failed to connect to the database.")

    except Error as e:
        # Handle MySQL specific errors
        print("Database Error", f"An error occurred: {e}")

    except Exception as e:
        # Handle any other errors
        print("Error", f"An unexpected error occurred: {e}")

    finally:
        # Ensure that the connection is closed if it was opened
        if connection.is_connected():
            connection.close()

def on_search(event):
    query = entry.get()
    fetch_data(query)
#fetch_data_from_db())
entry.bind("<KeyRelease>", on_search)

# Create a Treeview (scrollable table) # Replace with your actual column names--------------------------------
treeview = ttk.Treeview(frame, columns=("ID", "ProductName", "Category", "Price", "Quantity", "Warranty"), show="headings")
treeview.heading("ID", text="ID")
treeview.heading("ProductName", text="ProductName")
treeview.heading("Category", text="Category")
treeview.heading("Price", text="Price")
treeview.heading("Quantity", text="Quantity")
treeview.heading("Warranty", text="Warranty")

treeview.column("ID", width=50, anchor="center")
treeview.column("ProductName", width=340, anchor="w")
treeview.column("Category", width=180, anchor="center")
treeview.column("Price", width=120, anchor="center")
treeview.column("Quantity", width=80, anchor="center")
treeview.column("Warranty", width=120, anchor="center")

style = ttk.Style()
font = Font(family="Helvetica", size=14)  # You can change the font and size here
style.configure("Treeview.Heading", font=font)  # For column headers
style.configure("Treeview", font=font)  # For the data rows

fetch_data()
# Add a vertical scrollbar
vsb = ttk.Scrollbar(frame, orient="vertical", command=treeview.yview)
treeview.configure(yscrollcommand=vsb.set)
vsb.pack(side="right", fill="y")

# Insert data into the table
# Add Item page below------------------------------------------------------------------------------

def submit_item():
    name = iitem_namei.get()
    cat = category.get()
    quantity = qty.get()
    item_price = price.get()
    warr = warranty.get()
    vend = vendor.get()
    desc = description.get("1.0", tk.END).strip()
    add_time = added_datetime.get()

    if not name or not cat or not quantity or not item_price or not warr:
        messagebox.showwarning("Input Error", "Please fill all required fields.")
        print(f"name: '{name}', cat: '{cat}', qty: '{quantity}', price: '{item_price}', warr: '{warr}'")

        return

    try:
        connection = mysql.connector.connect(
            host="localhost",
            user="root",  # Replace with your MySQL username
            password="",  # Replace with your MySQL password
            database="inventory"  # Replace with your database name
        )
        connection.is_connected()
        cursor = connection.cursor()

        query = """
                INSERT INTO products (ProductName, Category, Price, Quantity, Warranty, Description)
                VALUES (%s, %s, %s, %s, %s, %s)
            """
        values = (name, cat, int(item_price), int(quantity), warr, desc)

        cursor.execute(query, values)
        connection.commit()

        messagebox.showinfo("Success", "Item added to database successfully!")

        # Optional: Clear form fields
        iitem_namei.delete(0, tk.END)
        category.set('')
        qty.delete(0, tk.END)
        price.delete(0, tk.END)
        warranty.delete(0, tk.END)
        vendor.delete(0, tk.END)
        description.delete('1.0', tk.END)

    except Error as e:
        messagebox.showerror("Database Error", f"Error: {e}")
    finally:
        if connection.is_connected():
            cursor.close()
            connection.close()

    messagebox.showinfo("Success", "Item added successfully ! Please Refresh Yor Inventory Page")

label_font = ("Arial", 12)
entry_font = ("Arial", 12)

# === Row 1: Item Name + Category ===
tk.Label(additem, text="Item Name:", font=label_font).place(x=50, y=30)
iitem_namei = tk.Entry(additem, font=entry_font, width=30,
                     highlightthickness=1, highlightbackground="black", highlightcolor="black")
iitem_namei.place(x=160, y=30)

tk.Label(additem, text="Category:", font=label_font).place(x=600, y=30)
category = ttk.Combobox(additem, font=entry_font, width=28)
category['values'] = ("Processor", "Motherboard", "RAM", "SSD", "Gaming Case", "Cooling Fan", "Power Supply", "Keyboard", "Mouse", "Headset")
category.place(x=700, y=30)

# === Row 2: Quantity + Price ===
tk.Label(additem, text="Quantity:", font=label_font).place(x=50, y=110)
qty = tk.Entry(additem, font=entry_font, width=30,
                     highlightthickness=1, highlightbackground="black", highlightcolor="black")
qty.place(x=160, y=110)

tk.Label(additem, text="Price:", font=label_font).place(x=600, y=110)
price = tk.Entry(additem, font=entry_font, width=30,
                     highlightthickness=1, highlightbackground="black", highlightcolor="black")
price.place(x=700, y=110)

# === Row 3: Warranty + Vendor ===
tk.Label(additem, text="Warranty:", font=label_font).place(x=50, y=190)
warranty = tk.Entry(additem, font=entry_font, width=30,
                     highlightthickness=1, highlightbackground="black", highlightcolor="black")
warranty.place(x=160, y=190)

tk.Label(additem, text="Vendor:", font=label_font).place(x=600, y=190)
vendor = tk.Entry(additem, font=entry_font, width=30,
                     highlightthickness=1, highlightbackground="black", highlightcolor="black")
vendor.place(x=700, y=190)

# === Row 4: Description ===
tk.Label(additem, text="Description:", font=label_font).place(x=50, y=270)
description = tk.Text(additem, font=entry_font, width=95, height=5,
                     highlightthickness=1, highlightbackground="black", highlightcolor="black")
description.place(x=160, y=270)

# === Row 5: Time & Date + Submit ===
tk.Label(additem, text="Added On:", font=label_font).place(x=60, y=425)
added_datetime = tk.Entry(additem, font=entry_font, width=25, state='readonly')
added_datetime.place(x=160, y=425)

# Set date/time automatically
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
added_datetime.config(state='normal')
added_datetime.insert(0, now)
added_datetime.config(state='readonly')

# Submit Button
submit_btn = tk.Button(additem, text="Add Item", font=("Arial", 14), bg="green", fg="white", command=submit_item)
submit_btn.place(x=700, y=420, width=150, height=40)

# End of the add item page---------------------------------------------

#Start of the setting page---------------------------------------------

def dlt_item():
    selected_value = ditem_name.get()

    if not selected_value:
        messagebox.showwarning("Selection Error", "Please select an item to delete.")
        return

    # Extract only the product name before the hyphen
    selected_item = selected_value.split(" - ")[0].strip()

    try:
        connection = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="inventory"
        )
        cursor = connection.cursor()

        delete_query = "DELETE FROM products WHERE ProductName = %s"
        cursor.execute(delete_query, (selected_item,))
        connection.commit()

        if cursor.rowcount > 0:
            messagebox.showinfo("Success", f"Item '{selected_item}' deleted successfully.")
        else:
            messagebox.showwarning("Not Found", f"No item named '{selected_item}' found in the database.")

        load_items()

    except Error as e:
        messagebox.showerror("Database Error", f"Error: {e}")
    finally:
        if connection.is_connected():
            cursor.close()
            connection.close()

# Function to load product names into dropdown
def load_items():
    try:
        connection = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="inventory"
        )
        cursor = connection.cursor()

        cursor.execute("SELECT ProductName, Category, Quantity FROM products")
        results = cursor.fetchall()

        formatted_items = [f"{row[0]} - {row[1]} - Qty: {row[2]}" for row in results]
        ditem_name['values'] = formatted_items
        ditem_name.set('')

    except Error as e:
        messagebox.showerror("Database Error", f"Error loading items: {e}")
    finally:
        if connection.is_connected():
            cursor.close()
            connection.close()

def addoneitem():
    selected_value = ditem_name.get()
    if not selected_value:
        messagebox.showwarning("Selection Error", "Please select an item to increment quantity.")
        return

    # Extract ProductName from selected dropdown value
    product_name = selected_value.split(" - ")[0].strip()

    try:
        connection = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="inventory"
        )
        cursor = connection.cursor()

        # Step 1: Get current quantity
        cursor.execute("SELECT Quantity FROM products WHERE ProductName = %s", (product_name,))
        result = cursor.fetchone()

        if result is None:
            messagebox.showerror("Error", f"Item '{product_name}' not found.")
            return

        current_qty = result[0]
        new_qty = current_qty + 1

        # Step 2: Update quantity in the database
        cursor.execute("UPDATE products SET Quantity = %s WHERE ProductName = %s", (new_qty, product_name))
        connection.commit()

        messagebox.showinfo("Success", f"Quantity of '{product_name}' increased to {new_qty}.")

        # Refresh the dropdown to show updated qty
        load_items()


    except Error as e:
        messagebox.showerror("Database Error", f"Error: {e}")
    finally:
        if connection.is_connected():
            cursor.close()
            connection.close()

def soldoneitem():
    selected_value = ditem_name.get()
    if not selected_value:
        messagebox.showwarning("Selection Error", "Please select an item to mark as sold.")
        return

    # Extract ProductName
    product_name = selected_value.split(" - ")[0].strip()

    try:
        connection = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="inventory"
        )
        cursor = connection.cursor()

        # Step 1: Get current quantity
        cursor.execute("SELECT Quantity FROM products WHERE ProductName = %s", (product_name,))
        result = cursor.fetchone()

        if result is None:
            messagebox.showerror("Error", f"Item '{product_name}' not found.")
            return

        current_qty = result[0]

        if current_qty <= 0:
            messagebox.showwarning("Out of Stock", f"'{product_name}' is already out of stock.")
            return

        new_qty = current_qty - 1

        # Step 2: Update quantity
        cursor.execute("UPDATE products SET Quantity = %s WHERE ProductName = %s", (new_qty, product_name))
        connection.commit()

        messagebox.showinfo("Success", f"Marked 1 unit of '{product_name}' as sold. Remaining: {new_qty}")

        cursor.execute("SELECT Quantity, Price, Category FROM products WHERE ProductName = %s", (product_name,))
        result = cursor.fetchone()

        if not result:
            messagebox.showerror("Error", f"Item '{product_name}' not found in products.")
            return

        current_qty, unit_price, category = result

        if current_qty <= 0:
            messagebox.showwarning("Out of Stock", f"'{product_name}' is out of stock.")
            return

        # Calculate new values
        new_qty = current_qty - 1
        unit_price = float(unit_price)
        profit = round(unit_price * 0.15, 2)
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Step 2: Update quantity in products table
        cursor.execute(
            "UPDATE products SET Quantity = %s WHERE ProductName = %s",
            (new_qty, product_name)
        )

        # Step 3: Insert or Update into sold_items
        cursor.execute("SELECT Quantity, Profit FROM sold_items WHERE ProductName = %s", (product_name,))
        sold_item = cursor.fetchone()

        if sold_item:
            # Update existing row
            sold_qty = sold_item[0] + 1
            total_profit = round(float(sold_item[1]) + profit, 2)

            cursor.execute("""
                        UPDATE sold_items
                        SET Quantity = %s, Profit = %s, UpdatedAt = %s
                        WHERE ProductName = %s
                    """, (sold_qty, total_profit, now, product_name))
        else:
            # Insert new row
            cursor.execute("""
                        INSERT INTO sold_items (ProductName, Category, Quantity, UnitPrice, Profit, UpdatedAt)
                        VALUES (%s, %s, %s, %s, %s, %s)
                    """, (product_name, category, 1, unit_price, profit, now))

        # Commit changes
        connection.commit()

        # Refresh the dropdown list
        load_items()

    except Error as e:
        messagebox.showerror("Database Error", f"Error: {e}")
    finally:
        if connection.is_connected():
            cursor.close()
            connection.close()


label_font = ("Arial", 15, "bold")
entry_font = ("Arial", 15)

tk.Label(setting, text="Set Item :", font=label_font).place(x=175, y=30)

ditem_name = ttk.Combobox(setting, font=entry_font, width=60)
ditem_name.place(x=280, y=30)


add_btn = tk.Button(setting, text="Add 01", font=("Arial", 15), bg="Yellow", fg="Black", command=addoneitem)
add_btn.place(x=200, y=100, width=100, height=30)

sold_btn = tk.Button(setting, text="Sold 01", font=("Arial", 15), bg="Green", fg="White", command=soldoneitem)
sold_btn.place(x=520, y=100, width=100, height=30)

dlt_btn = tk.Button(setting, text="Delete", font=("Arial", 15), bg="Red", fg="white", command=dlt_item)
dlt_btn.place(x=820, y=100, width=100, height=30)


load_items()

treeview.pack(fill="both", expand=True)

summary_content = f"""\
This Python-based Inventory Management System makes managing your shop’s stock simple and stress-free. 

Built with a clean and user-friendly interface using Tkinter, the system lets you:
• Add, update, or remove items from your inventory
• Monitor stock levels in real time
• Automatically record each sale and calculate profit
• Save and retrieve all your data from a MySQL database
• Keep a clear log of every transaction, complete with timestamps

Whether it's a tech store, grocery shop, clothing boutique, or hardware store — this system is designed to work for you.  
It’s fast, flexible, and ready to support your shop from day one.

Created by: Dasindu Dilvan Wijethunga
Created Date: 13/04/2025
"""

summary_text = tk.Text(setting, font=("Arial", 14), wrap='word', bg="#fff", bd=0, relief="groove", width=135, height=18)
summary_text.insert(tk.END, summary_content)
summary_text.config(state='disabled')  # Make it read-only
summary_text.place(x=100, y=190)


show_frame(homepage)
window.resizable(False, False)
window.mainloop()
